### ISSUE TITLE
motif search

### ISSUE THREAD

**Issue by anna-panchenko** [neksa/mutagene#33]
It is not clear which motif is used by default. If "--motif" argument is missing, the program is hanging for long time and then returns an error. It should return a warning: "motif is not specified" in the beginning.
>mutagene motif -i sample.maf

Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/__main__.py", line 113, in <module>
    MutaGeneApp()
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/__main__.py", line 104, in __init__
    parser_class.callback(args)
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/cli/motif_menu.py", line 149, in callback
    MotifMenu.search(args)
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/cli/motif_menu.py", line 127, in search
    dump_matches=args.save_motif_matches) if mutations_with_context is not None else []
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/motifs/__init__.py", line 46, in identify_motifs
    motifs = get_known_motifs()
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/io/motifs.py", line 21, in get_known_motifs
    with open(fname, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/io/../data/motifs/motifs.json'
(venv) [hpc4498@caclogin02 mutagene]$
(venv) [hpc4498@caclogin02 mutagene]$ mutagene motif -i TCGA.COAD.mutect.somatic.maf -w 250 -t 0.1 -o tmp1 -g hg38
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/__main__.py", line 113, in <module>
    MutaGeneApp()
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/__main__.py", line 104, in __init__
    parser_class.callback(args)
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/cli/motif_menu.py", line 149, in callback
    MotifMenu.search(args)
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/cli/motif_menu.py", line 127, in search
    dump_matches=args.save_motif_matches) if mutations_with_context is not None else []
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/motifs/__init__.py", line 46, in identify_motifs
    motifs = get_known_motifs()
  File "/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/io/motifs.py", line 21, in get_known_motifs
    with open(fname, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/global/home/hpc4498/venv/lib/python3.7/site-packages/mutagene/io/../data/motifs/motifs.json'

**Comment by neksa** [comment]
It was a packaging error. Please update to 0.9.0.1
By default it will search for all known motifs.
