### ISSUE TITLE
ambiguous error message

### ISSUE THREAD

**Issue by anna-panchenko** [neksa/mutagene#38]
Specifying a wrong format type (VCF, not MAF) produces an uninformative message:

(env_mutagene) Annas-MBP:mutagene panch$ mutagene signature identify -i data_mutations_extended.txt -g hg19 -s 49 -U -b -f VCF
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/__main__.py", line 113, in <module>
    MutaGeneApp()
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/__main__.py", line 104, in __init__
    parser_class.callback(args)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/cli/signature_menu.py", line 117, in callback
    self.identify(args)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/cli/signature_menu.py", line 94, in identify
    mutations, processing_stats = read_auto_profile(args.infile, fmt=args.input_format, asm=args.genome)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/io/mutations_profile.py", line 115, in read_auto_profile
    mutations, processing_stats = read_VCF_profile(mutations_lines, asm)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/io/mutations_profile.py", line 234, in read_VCF_profile
    pos = int(col_list[1])  # VCF POS
ValueError: invalid literal for int() with base 10: 'Entrez_Gene_Id'

**Comment by neksa** [comment]
It's a Python exception.

Are you trying to process MAF file as a VCF?

**Comment by anna-panchenko** [comment]
yes

**Comment by anna-panchenko** [comment]
the users will not always know which format they are using
