### ISSUE TITLE
Ranking, can not override profile 

### ISSUE THREAD

**Issue by anna-panchenko** [neksa/mutagene#56]
$ mutagene -v rank -g hg38 -i TCGA.COAD.mutect.somatic.maf --profile TCGA.COAD.mutect.somatic.maf
INFO Loaded 230248 mutations
INFO Loaded 190240 protein mutations in 399 samples skipped 74543 protein mutations
INFO Cohort size: 399
INFO Profile overridden
INFO THRESHOLD_DRIVER: 8.030647e-05
INFO THRESHOLD_PASSENGER: 0.003440945
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/__main__.py", line 113, in <module>
    MutaGeneApp()
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/__main__.py", line 104, in __init__
    parser_class.callback(args)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/cli/rank_menu.py", line 114, in callback
    rank(protein_mutations, args.outfile, profile, cohort_aa_mutations, cohort_size, args.threshold_driver, args.threshold_passenger)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/mutability/mutability.py", line 138, in rank
    mutation_model = calculate_base_substitution_mutability(profile, cohort_size)
  File "/Users/panch/mutagene/env_mutagene/lib/python3.7/site-packages/mutagene/mutability/mutability.py", line 111, in calculate_base_substitution_mutability
    assert len(counts_profile) == 96
AssertionError

**Comment by neksa** [comment]
if `-i TCGA.COAD.mutect.somatic.maf ` is supplied, profile will be calculated from that MAF file, profile override is not necessary.

In order to override profile you would need the profile itself in "profile" format:

```
mutagene profile -g hg38 -i TCGA.COAD.mutect.somatic.maf -o COAD.profile
```

Once it's ready we can use the profile file
```
mutagene profile -g hg38 -i TCGA.COAD.mutect.somatic.maf -o COAD.profile
```

**Comment by shandy79** [comment]
Suggested fix is to catch the error and display a meaningful error message reminding users of the profile subcommand.

**Comment by shandy79** [comment]
Closed w/PR 57
